### ISSUE TITLE
Support for Rust-only backends

### ISSUE THREAD

**Issue by bede** [sstadick/gzp#65]
Hi @sstadick, thanks for making this useful library.
I would like to use gzp in Deacon for output compression. It appears that the Rust-only `deflate_rust` backend is no longer supported after 0.11.3. Presumably there is a good reason you dropped support for this in favour of libz-ng. However in my naive testing so far there is little practical benefit to using libz-ng for my application over deflate_rust, and I would like to avoid non-Rust dependencies if possible. I am seeing nice speedups and am eager to implement.

Might it be possible to restore support for a Rust-only backend like deflate_rust? Or help me understand why this is no longer supported. Also, is zlib-rs a candidate?

Thanks,
Bede

**Comment by sstadick** [comment]
Hi @bede!

Does enabling the `rust_deflate` feature not work? I don't think it was ever specifically removed / support dropped at any point. I do want to have a fully rust backend available for this library for sure. So if that's not working I'll try to fix it!

Feature is here: https://github.com/sstadick/gzp/blob/072c3bbe9f68e68aee56ecc2f7a2990fcbd4ab08/Cargo.toml#L29

**Comment by bede** [comment]
Oh silly me, it's working great. Something errored for me initially and I misunderstood the changelog. Thanks!

**Comment by bede** [comment]
Hi again, forgive me if this is user error, but after uninstalling cmake and running `cargo clean && cargo build -r` I'm getting cmake / libz-ng-sys related failures again with `2.0.0`. Are you able to replicate or suggest what I could be doing wrong? It seems libz-ng-sys is being pulled in despite `deflate_rust`.

This is my Cargo.toml line (`optional=true` so that it can be disabled for fast dev builds):
```
gzp = { version = "2.0", default-features = false, features = ["deflate_rust"], optional = true }
```

Build fails with:
```
error: failed to run custom build command for `libz-ng-sys v1.1.22`
```

**Comment by sstadick** [comment]
Yep! That's an issue, thank you for persisting!

libz-ng-sys was not behind a feature gate, introduced here: https://github.com/sstadick/gzp/commit/a234716fd172034dca606ace20f27f4147ee1ae7#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542

Fix incoming here: https://github.com/sstadick/gzp/pull/66

**Comment by bede** [comment]
Excellent, I'll test once home, thanks :)

**Comment by bede** [comment]
Now working great via patch

**Comment by sstadick** [comment]
Nice! I'll have that merged and released tomorrow! Thanks again for making an issue and catching that.

**Comment by sstadick** [comment]
Fixed in v2.0.1. Please re-open if you hit any other issues!

**Comment by bede** [comment]
Lovely, thanks!

**Comment by vrmiguel** [comment]
Sorry @sstadick, I'm assuming I'm noobing out here, but this is still not working for me.

I'm trying to build `ouch`, which currently has this in Cargo.toml:

```toml
gzp = { version = "2.0.0", default-features = false, features = [
    "snappy_default",
] }
```

When building it, I get the `use of unresolved module or unlinked crate libz_ng_sys` issue. Curiously, the [CI jobs of ouch](https://github.com/ouch-org/ouch/actions/runs/19279357918/job/55126752776?pr=886) manage to build the project fine, maybe some sort of cache issue? I've tried `cargo clean` and `rm -rf ~/.cargo/registry`

I've also tried:

### Bumping to 2.0.1

```toml
gzp = { version = "2.0.1", default-features = false, features = [
    "snappy_default",
] }
```

Didn't work for me

### Bumping to 2.0.1 and adding `deflate_rust`

```toml
gzp = { version = "2.0.1", default-features = false, features = [
    "snappy_default",
    "deflate_rust"
] }
```

Still no luck.


It only worked for me if with `default-features` enabled. Is that intended?

**Comment by sstadick** [comment]
@vrmiguel - thanks for bringing this up! Similar to the original issue, the feature flags around libz-ng-sys got messed up. https://github.com/sstadick/gzp/pull/67 should fix it. I'm able to compile ouch locally with these changes and default-features set to false for gzp.

**Comment by sstadick** [comment]
@vrmiguel see v2.0.2. Please reopen if it doesn't work!
